<h3 style="margin-bottom:0">a) NumPy</h3>

<h4 style="margin-bottom:0">1) Importing NumPy</h4>

In [1]:
import numpy as np

<h4 style="margin-bottom:0">2) Creating Array</h4>

Create an array (4x4) named "array" that has consecutive numbers from 1 to 16.

In [2]:
array = np.arange(1, 17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Check the shape of the array to make sure you created it correctly.

In [3]:
array.shape

(4, 4)

<h4 style="margin-bottom:0">3) Indexing and Slicing</h4>

Retrieve elements "10,11 and 12".

In [4]:
array[2,1:4]

# or;
# array[np.logical_and(array>9, array<13)]

array([10, 11, 12])

Retrieve all elements that are greater than 9.

In [5]:
array[array>9]

array([10, 11, 12, 13, 14, 15, 16])

Retrieve all odd numbers.

In [6]:
array[(array %2 != 0)]

# Alternative;
# arrayodd = array.reshape(array.size)
# for x in np.nditer(arrayodd):
  # if (arrayodd[x-1] % 2 != 0) :
   # print(arrayodd[x-1], end= " ")

array([ 1,  3,  5,  7,  9, 11, 13, 15])

Retrieve all numbers that are at the edges of your array (1, 4, 13 and 16).

In [7]:
array[::3,::3]

array([[ 1,  4],
       [13, 16]])

<h4 style="margin-bottom:0">4) Array Manipulation</h4>

Delete the last <b>row </b>.

In [8]:
array_del = np.delete(array, 3, 0)
array_del

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Add a new <b> column </b> that has elements 17, 18 and 19.

In [9]:
new_column = [17, 18, 19]
new_array = np.insert(array_del, 4, new_column, axis=1)
new_array

array([[ 1,  2,  3,  4, 17],
       [ 5,  6,  7,  8, 18],
       [ 9, 10, 11, 12, 19]])

<h3 style="margin-bottom:0">b) Pandas</h3>

Dataset shows fictional transactions between fictional companies that sell <b> Qutrian </b> (a made up metal) in 2020. Each individual elements are explained as follows:
<ul>
<li>Seller: seller company name</li>
<li>Buyer: buyer company name</li>
<li>Quantity: selling quantity (in tons), can be from 0 to 800 due to limitations.</li>
<li>Price: selling price (in $), can be from 0 to 10 due to limitations.</li>
<li>Date: transaction date, have to be in 2020.</li></ul>



<h4 style="margin-bottom:0">1) Import Pandas</h4>

Import Pandas library of Python:

In [10]:
import pandas as pd

<h4 style="margin-bottom:0">2) Import Data</h4>

Import the "data.csv" file.

In [13]:
df = pd.read_csv('C:\\Users\Gizem\Files\data.csv', sep='/')

Look at whether the data is imported correctly, check top 5 rows.

In [14]:
df.head(5)

seller             buyer  quantity         price   date
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769704e+13  43831
1               Diluc     Qutrian Force     477.0  2.679111e+14  43831
2               Cygen          Qutrianx     722.0  1.255434e+14  43831
3      Iconic Qutrian             Grids     779.0  2.887408e+14  43831
4         USA Qutrian      Qutrian Gold     750.0  3.522572e+14  43832

<h4 style="margin-bottom:0">3) Cleanse Data</h4>

<li>when we check price and date columns above, we see there is something wrong. It seems price information is written as very big numbers and date seems strange, perhaps there is a way to convert this Excel format into pandas format.</li>
<li>There may be missing values.

<h5 style="margin-bottom:0">i) Price & Date</h5>

As mentioned above, price information seems strange. This is because they forgot to put a dot after first digit. Also, even if this was a correct column, there would be a huge amount of decimal points that is not necessary in our analysis. So, 3 decimal points is enough for us. Lets transform it and show first 5 line to s
<br>


In [15]:
#df.loc[df['price'].isnull()]
# Firstly check whether there are null values in price column. 
# Since there are null values, write if clause in convertion functions below;

# Convert numeric values to string in order to add dot after first character
df['price'] = df['price'].apply(lambda x: str(x) if str(x) != 'nan' else None)

# Get first 4 digits since we want to see only 3 decimals in the end
df['price'] =df['price'].str[:4]

#Add dot after first digit
df['price'] = df['price'].str[:1] + "." + df['price'].str[1:]

#Change datatype from string to number
df['price'] = df['price'].apply(lambda x: pd.to_numeric(x) if pd.to_numeric(x) != 'nan' else None)

df


seller             buyer  quantity  price   date
0     Qutrian Engineered  Qutrian All-Star     110.0  1.769  43831
1                  Diluc     Qutrian Force     477.0  2.679  43831
2                  Cygen          Qutrianx     722.0  1.255  43831
3         Iconic Qutrian             Grids     779.0  2.887  43831
4            USA Qutrian      Qutrian Gold     750.0  3.522  43832
...                  ...               ...       ...    ...    ...
3142              Origin     Japan Qutrian     496.0  7.950  44196
3143     Qutrian Network   Qutrian Crusade     404.0  3.946  44196
3144         Qutrianzoid             Omega     380.0  1.602  44196
3145               Cygen             Bliss     360.0  5.474  44196
3146    Qutrian All-Star             Omega     702.0  2.036  44196

[3147 rows x 5 columns]

Date information is also strange. This is due to excel date format. Lets convert this format into ISO 8601 format (yyyy-mm-dd).

In [16]:
import xlrd
from datetime import datetime

df["date"] = df["date"].apply(lambda x: datetime(*xlrd.xldate_as_tuple(x, 0)))
df

seller             buyer  quantity  price       date
0     Qutrian Engineered  Qutrian All-Star     110.0  1.769 2020-01-01
1                  Diluc     Qutrian Force     477.0  2.679 2020-01-01
2                  Cygen          Qutrianx     722.0  1.255 2020-01-01
3         Iconic Qutrian             Grids     779.0  2.887 2020-01-01
4            USA Qutrian      Qutrian Gold     750.0  3.522 2020-01-02
...                  ...               ...       ...    ...        ...
3142              Origin     Japan Qutrian     496.0  7.950 2020-12-31
3143     Qutrian Network   Qutrian Crusade     404.0  3.946 2020-12-31
3144         Qutrianzoid             Omega     380.0  1.602 2020-12-31
3145               Cygen             Bliss     360.0  5.474 2020-12-31
3146    Qutrian All-Star             Omega     702.0  2.036 2020-12-31

[3147 rows x 5 columns]

<h5 style="margin-bottom:0">ii) Null Values</h5>

Now, we have converted our strange variables into meaningful ones. We should deal with null values. Before dealing with values, lets look at all of the rows that have at least one null value.

In [17]:
df[df.isna().any(axis=1)]

seller               buyer  quantity  price       date
490    Qutrian Trust                 NaN     563.0  5.993 2020-02-28
793   French Qutrian            Qutrianx       3.0    NaN 2020-04-03
1123           Grids         USA Qutrian       NaN  1.149 2020-05-10
1568           Vital            Qutrianx      97.0    NaN 2020-07-02
1649             NaN               Diluc     670.0  2.721 2020-07-11
1783      Queentrian                 NaN     674.0  7.218 2020-07-25
1925            Ca$h               Omega     577.0    NaN 2020-08-09
2053          Vertex                 NaN     348.0  1.585 2020-08-24
2179             NaN     Qutrian Essence     541.0  2.776 2020-09-08
2318           Bliss  Qutrian Engineered     776.0    NaN 2020-09-24
2436  French Qutrian                 NaN     443.0  6.404 2020-10-08
2564             NaN               Diluc     241.0  2.635 2020-10-24
2686   Qutrian Trust                 NaN      63.0  2.399 2020-11-09
2936          Vertex            Qutrianx       5.0    NaN 2020-12-09
3126    Best Qutrian                 NaN     346.0  2.465 2020-12-29

Now, fill null values for "quantity" and "price" with the mean values of those columns. After filling them, show the rull nows again to ensure only seller or buyer have null values.

In [18]:
#Fill null values of quantity with the mean of quantity column
df['quantity']= df['quantity'].fillna(df['quantity'].mean())

#Fill null values of price with the mean of price column
df['price']= df['price'].fillna(df['price'].mean())

# Check whether there are null values: df.loc[df['price'].isnull()]

<h5 style="margin-bottom:0">iii) Limitations</h5>

Finally, to clean the data, we will need to see whether certain entries are below or above limitations. As different types of entries need a different type of corrections, we will consider them separately.

First, let's have a look at whether there is a quantity or price that is off limits.

In [19]:
# I will use standard deviation method to detect outliers.
## Lets firstly check for quantity:

upper_limit_quantity = df['quantity'].mean() + 3 * df['quantity'].std()
lower_limit_quantity = df['quantity'].mean() - 3 * df['quantity'].std()

print("Upper limit Quantity: ", upper_limit_quantity)
print("Lower Limit Quantity: ", lower_limit_quantity)

# Any value which is more then upper limit and less then lower limit considered as outlier. 
# Since the lower limit is less then zero but quantity cannot be minus. I will set lower limit as zero.
# Off-limit rows for quantity: df[(df['quantity'] > upper_limit_quantity) | (df['quantity'] < 0)]

## Secondly check for price:

upper_limit_price = df['price'].mean() + 3 * df['price'].std()
lower_limit_price = df['price'].mean() - 3 * df['price'].std()

print("Upper limit Price: ", upper_limit_price)
print("Lower Limit Price: ", lower_limit_price)

# Any value which is more then upper limit and less then lower limit considered as outlier. 
# Since the lower limit is less then zero but quantity cannot be minus. I will set lower limit as zero.
# Off-limit rows for price: df[(df['price'] > upper_limit_price) | (df['price'] < 0)]

df[(df['price'] > upper_limit_price) | (df['price'] < 0) | (df['quantity'] > upper_limit_quantity) | (df['quantity'] < 0)]



Upper limit Quantity:  1201.9981788679088
Lower Limit Quantity:  -409.2639131336431
Upper limit Price:  10.071406684651883
Lower Limit Price:  -3.681388861609235


seller           buyer  quantity  price       date
369      Qutrian Gold           Vista    -118.0 -0.237 2020-02-13
572             Alpha        Qutrianx    -300.0  2.592 2020-03-08
724    German Qutrian  French Qutrian    7777.0  2.925 2020-03-27
1911  Swedish Qutrian    Best Qutrian    1950.0  2.013 2020-08-08
1998  Swedish Qutrian     USA Qutrian     262.0 -0.257 2020-08-18
2504      Qutrian Box        Qutrianx    2231.0  2.828 2020-10-16

There are many things that can be done to deal with those values. To practice lets use lambda functions.
<ul>
<li>If there is a negative number, take absolute value of it (because "minus" sign is most probably an accident) </li>
<li>If there is a number above the limit, simply set it to upper limit.</li>
</ul>

In [20]:
#Take the absolute values of price and quantity:
df['price'] = df['price'].abs()
df['quantity'] = df ['quantity'].abs()

#Replace the ones which are greater then upper limit:
df['price'] = df['price'].apply(lambda x: upper_limit_price if x> upper_limit_price else x)
df['quantity'] = df['quantity'].apply(lambda x: upper_limit_quantity if x> upper_limit_quantity else x)

#Lets check again the off-limits:
df[(df['price'] > upper_limit_price) | (df['price'] < 0) | (df['quantity'] > upper_limit_quantity) | (df['quantity'] < 0)]


Empty DataFrame
Columns: [seller, buyer, quantity, price, date]
Index: []

Then, there can be some values for "date" that is not in 2020. Simply sort date value to see extreme values.

In [21]:
df.sort_values('date', ascending=False)

seller             buyer  quantity  price       date
1450               Omega    Qutrian 4 Life     576.0  1.459 2058-10-16
1612      German Qutrian            Origin     282.0  3.418 2023-04-03
3146    Qutrian All-Star             Omega     702.0  2.036 2020-12-31
3139            Qutrianx     Bloom Qutrian      96.0  2.727 2020-12-31
3136               Aegis    Qutrian 4 Life     242.0  1.352 2020-12-31
...                  ...               ...       ...    ...        ...
2                  Cygen          Qutrianx     722.0  1.255 2020-01-01
3         Iconic Qutrian             Grids     779.0  2.887 2020-01-01
1                  Diluc     Qutrian Force     477.0  2.679 2020-01-01
0     Qutrian Engineered  Qutrian All-Star     110.0  1.769 2020-01-01
325                Cygen      Qutrian Boss     217.0  1.739 1937-12-20

[3147 rows x 5 columns]

There are some dates that are not in 2020. Here, we can simply convert those values into 2020 as they are probably a mistake. After converting, show your sorted date value again to visualize there is not an extreme value anymore.

In [22]:
#Change the type of the 'date' column to date to replace year
df['date'] = df['date'].dt.date

# Make all the year values equal to 2020
df['date'] = df['date'].apply(lambda x: x.replace(year=2020))

#Check whether they are all set to 2020
df.sort_values('date', ascending=False)

seller             buyer  quantity  price        date
3146    Qutrian All-Star             Omega     702.0  2.036  2020-12-31
3140         Qutrian Box   Turkish Qutrian     328.0  2.020  2020-12-31
3136               Aegis    Qutrian 4 Life     242.0  1.352  2020-12-31
3137                Ca$h            Origin     354.0  2.105  2020-12-31
3138               Grids       Qutrianzoid     687.0  1.396  2020-12-31
...                  ...               ...       ...    ...         ...
4            USA Qutrian      Qutrian Gold     750.0  3.522  2020-01-02
2                  Cygen          Qutrianx     722.0  1.255  2020-01-01
1                  Diluc     Qutrian Force     477.0  2.679  2020-01-01
3         Iconic Qutrian             Grids     779.0  2.887  2020-01-01
0     Qutrian Engineered  Qutrian All-Star     110.0  1.769  2020-01-01

[3147 rows x 5 columns]

<h4 style="margin-bottom:0">4) Querying Data</h4>

We have cleansed our data as much as we could. In this final step, you will need to query data to get useful information.

First, add a new column that shows revenue (quantity * price) and name it as "revenue", show first 5 columns.

In [23]:
df['revenue']= df['quantity']*df['price']
df.head(5)

seller             buyer  quantity  price        date   revenue
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769  2020-01-01   194.590
1               Diluc     Qutrian Force     477.0  2.679  2020-01-01  1277.883
2               Cygen          Qutrianx     722.0  1.255  2020-01-01   906.110
3      Iconic Qutrian             Grids     779.0  2.887  2020-01-01  2248.973
4         USA Qutrian      Qutrian Gold     750.0  3.522  2020-01-02  2641.500

Also, add a new column that indicates the month that the transaction occured and name it as "month". This will help us later. Show first 5 columns.

In [24]:
import datetime
df['month'] = pd.DatetimeIndex(df['date']).month
df.head(5)

seller             buyer  quantity  price        date  \
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769  2020-01-01   
1               Diluc     Qutrian Force     477.0  2.679  2020-01-01   
2               Cygen          Qutrianx     722.0  1.255  2020-01-01   
3      Iconic Qutrian             Grids     779.0  2.887  2020-01-01   
4         USA Qutrian      Qutrian Gold     750.0  3.522  2020-01-02   

    revenue  month  
0   194.590      1  
1  1277.883      1  
2   906.110      1  
3  2248.973      1  
4  2641.500      1

Lets find how much qutrian is sold (in tons) in each month.

In [25]:
# Assume that the seller column which contains "qutrian" sells only "qutrian", 
# and buyer column which contains "qutrian" buys only qutrian
# Therefore filter the rows which contains "qutrian" in seller or buyer firstly;
df_qutrian = df[df['seller'].str.contains('Qutrian' , na = False) | df['buyer'].str.contains('Qutrian' , na = False) ]

#then select the quantity column (in order to not show price or revenue)
df_qutrian_qty = df_qutrian[['seller', 'quantity', 'month']]

#Assume the quantity values are in tons, then take the sum of quantity by month
df_qutrian_sum = df_qutrian_qty.groupby('month').sum()

#sort in descending and show first 5 rows;
df_qutrian_sum.sort_values(['quantity'], ascending=False).head(5)


quantity
month               
12     104942.000000
5      104381.367133
7       96877.000000
1       96313.000000
9       95499.000000

Find mean price charged by each of the companies and find 5 cheapest companies and retrieve them.

In [26]:
# for the simplicity, lets choose seller and price columns first
df_company_pr = df[['seller', 'price']]
df_company_pr.groupby(['seller']).mean(['price'])

# sort ascending and get first 5 rows
df_company_pr.sort_values(['price'], ascending=True).head(5)

seller  price
369      Qutrian Gold  0.237
1998  Swedish Qutrian  0.257
2232      Qutrian Box  1.000
1652    Japan Qutrian  1.000
1065       UK Qutrian  1.001

Show the two companies that has the highest total revenue traded.

In [27]:
# for the simplicity, lets choose seller and revenue columns first
df_company_revenue = df[['seller', 'revenue']]

#then calculate total revenue for each company by group by
df_company_revenue2 = df_company_revenue.groupby(['seller']).sum()

# sort descending and get highest 2
df_company_revenue2.sort_values(['revenue']).head(2)

revenue
seller                   
Iconic Qutrian  51789.858
Queentrian      59149.415